baseURL = "https://example.edu"
languageCode = "en-us"
title = "Eric Qian"
theme = "avicenna"
googleAnalytics = "UA-154981437-1"
timeout=3000

[params]
  subtitle= "Senior Research Analyst"
  interests="Macroeconomics, business cycles, monetary economics, macroeconometrics"
  cv_name= "qian_eric_cv.pdf"
  

[[params.affilation]]
  name = "Federal Reserve Bank of New York"
  position = "Senior Research Analyst"



[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/eric-qian"



[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/ericyqian"


[[params.introduction.paragraph]]
  text="""I am a Senior Research Analyst at the Federal Reserve Bank of New York on the Time Series Analysis Team, working on academic research, policy analysis, and macroeconomic forecasting. """

[[params.introduction.paragraph]]
  text="""I graduated with Highest Distinction from the University of North Carolina at Chapel Hill in 2018 with majors in __Mathematics (BS) and Statistics and Analytics (BS)__. Under the Robertson Scholars Program, a dual enrollment full scholarship program, I received a minor in __Economics__ from Duke University."""

[[params.introduction.paragraph]]
  text="""*All views expressed are my own, and do not reflect those of the Federal Reserve Bank of New York nor Federal Reserve System.*"""


[[params.publications]]
  year="Blog Articles"

[[params.publications.paper]]
    name = "Just Released: Historical Reconstruction of the New York Fed Staff Nowcast, 2002-15"
    authors = "Patrick Adams, Domenico Giannone, __Eric Qian__, and Argia M. Sbordone"
    dest  = "Liberty Street Economics (July 12, 2019)"
    link = "https://libertystreeteconomics.newyorkfed.org/2019/07/just-released-historical-reconstruction-of-the-new-york-fed-staff-nowcast-2002-15.html"

[[params.publications.paper]]
    name = "Global Trends in Interest Rates"
    authors = "Marco Del Negro, Domenico Giannone, Marc Giannoni, Andrea Tambalotti, Brandyn Bok, and __Eric Qian__"
    dest  = "Liberty Street Economics (February 27, 2019)"
    link = "https://libertystreeteconomics.newyorkfed.org/2019/02/global-trends-in-interest-rates.html"
  

  [[params.publications.paper]]
    name = "Monitoring Economic Conditions during a Government Shutdown"
    authors = "Patrick Adams, Domenico Giannone, __Eric Qian__, and Argia M. Sbordone"
    dest  = "Liberty Street Economics (February 05, 2019)"
    link = "https://libertystreeteconomics.newyorkfed.org/2019/02/monitoring-economic-conditions-during-a-government-shutdown.html"


  [[params.publications.paper]]
    name = "Opening the Toolbox: The Nowcasting Code on GitHub"
    authors = "Patrick Adams, Brandyn Bok, Daniele Caratelli, Domenico Giannone, __Eric Qian__, Argia M. Sbordone, Camilla Schneier, and Andrea Tambalotti"
    dest  = "Liberty Street Economics (August 10, 2018)"
    link = "https://libertystreeteconomics.newyorkfed.org/2018/08/opening-the-toolbox-the-nowcasting-code-on-github.html"
  
